- name: Setup VPN host
  hosts: vpn
  become: true
  tasks:
    - name: Update host
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Install necessary packages
      ansible.builtin.apt:
        pkg:
        - ca-certificates
        - curl
        update_cache: true
        cache_valid_time: 86400

    - name: Create directory for storing docker gpg key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download docker gpg key
      ansible.builtin.uri:
        url: https://download.docker.com/linux/ubuntu/gpg
        method: GET
        creates: /etc/apt/keyrings/docker.asc
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: Add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable
        state: present

    - name: Install docker
      ansible.builtin.apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        update_cache: true
        cache_valid_time: 86400

    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        append: true
        groups: docker
